
CREATE PROCEDURE dbo.usp_TruncateParameterTables
AS
BEGIN
truncate table dbo.t_pipeline_linkedservice_parameters
truncate table dbo.t_pipeline_dataset_parameters
truncate table dbo.t_pipeline_activity_parameters
truncate table dbo.t_pipelines_steps
truncate table dbo.t_pipeline_datasets
truncate table dbo.t_pipeline_linkedservices
truncate table dbo.t_pipeline_tables_tobemoved
END